SAMPLES:
     #['BIG']
     [
     #OTHER COHORTS
     #BRIP01, BRIP02, BRIP03, BRIP04, BRIP05, BRIP06, BRIP07, BRIP08, BRIP100,
     #BRIP101, BRIP102, BRIP103, BRIP104, BRIP105, BRIP106, BRIP107, BRIP108, BRIP109, BRIP110, BRIP111, BRIP112, BRIP113,
     #BRIP114, BRIP115, BRIP116, BRIP117, BRIP118, BRIP119, BRIP120, BRIP121, BRIP122, BRIP123, BRIP124, BRIP125, BRIP126, BRIP127,
     #BRIP128, BRIP15, BRIP16, BRIP17, BRIP18, BRIP19, BRIP20, BRIP21, BRIP22, BRIP23, BRIP24, BRIP25, BRIP26, BRIP27, BRIP28, BRIP29, BRIP30,
     #BRIP31, BRIP32, BRIP33, BRIP34, BRIP35, BRIP36, BRIP37, BRIP38, BRIP39, BRIP40, BRIP41, BRIP42, BRIP43, BRIP44, BRIP45, BRIP46, BRIP47, BRIP48,
     #BRIP49, BRIP50, BRIP51, BRIP52, BRIP53, BRIP54, BRIP55, BRIP56, BRIP57, BRIP58, BRIP59, BRIP60, BRIP61, BRIP62, BRIP63, BRIP64, BRIP65,
     #BRIP66, BRIP67, BRIP68, BRIP69, BRIP70, BRIP71, BRIP72, BRIP73,
     #BRIP74, BRIP75, BRIP76, BRIP77, BRIP78, BRIP79, BRIP80, BRIP81, BRIP82,
     #BRIP83, BRIP84, BRIP85, BRIP86, BRIP87, BRIP88, BRIP89, BRIP90, BRIP91,
     #BRIP92, BRIP93, BRIP94, BRIP95, BRIP96, BRIP97, BRIP98, BRIP99, BSUPM119,
     #BSUPM125, BSUPM129, BSUPM130, BSUPM132, BSUPM153, BSUPM170, BSUPM172, BSUPM174,
     #BSUPM178, BSUPM179, BSUPM180, BSUPM182, BSUPM184, BSUPM193, BSUPM200, BSUPM206, BSUPM207, BSUPM210, BSUPM268,
     #BATCH 1 FROM UCSF
     1464m_S63_L004, 1466m_S64_L004, 1467m_S65_L004, 1468m_S66_L004, 1472m_S67_L004, 1473m_S68_L004,
     1475m_S69_L004, 1476m_S70_L004, 1477m_S71_L004, 1478m_S72_L004, 1479m_S73_L004, 1483m_S74_L004,
     #BATCH 2 FROM UCSF
     mSARS2_15_S1_L004, mSARS2_16_S2_L004, mSARS2_17_S3_L004, mSARS2_18_S4_L004, mSARS2_19_S5_L004, mSARS2_20_S6_L004,
     mSARS2_21_S7_L004, mSARS2_22_S8_L004, mSARS2_23_S9_L004, mSARS2_24_S10_L004, mSARS2_25_S11_L004, mSARS2_26_S12_L004,
     mSARS2_27_S13_L004, mSARS2_28_S14_L004, mSARS2_29_S15_L004, mSARS2_30_S16_L004, mSARS2_31_S17_L004, mSARS2_32_S18_L004,
     mSARS2_33_S19_L004, mSARS2_34_S20_L004, mSARS2_35_S21_L004, mSARS2_36_S22_L004, mSARS2_37_S23_L004, mSARS2_38_S24_L004,
     mSARS2_39_S25_L004, mSARS2_40_S26_L004, mSARS2_41_S27_L004, mSARS2_42_S28_L004, mSARS2_43_S29_L004, mSARS2_44_S30_L004,
     mSARS2_45_S31_L004, mSARS2_46_S32_L004,
     #BATCH 3 FROM UCSF
     mSARS2_47_S1_L003, mSARS2_100_S86_L004, mSARS2_48_S2_L003, mSARS2_101_S87_L004, mSARS2_49_S3_L003, mSARS2_50_S4_L003,
     mSARS2_51_S5_L003, mSARS2_102_S88_L004, mSARS2_52_S6_L003, mSARS2_53_S7_L003, mSARS2_103_S89_L004, mSARS2_54_S8_L003,
     mSARS2_55_S9_L003, mSARS2_104_S90_L004, mSARS2_56_S10_L003, mSARS2_57_S11_L003, mSARS2_105_S91_L004, mSARS2_58_S12_L003,
     mSARS2_106_S92_L004, mSARS2_59_S13_L003, mSARS2_107_S93_L004, mSARS2_60_S14_L003, mSARS2_61_S15_L003, mSARS2_108_S94_L004,
     mSARS2_62_S16_L003, mSARS2_110_S96_L004, mSARS2_63_S17_L003, mSARS2_15_S33_L004, mSARS2_16_S34_L004, mSARS2_17_S35_L004,
     mSARS2_18_S36_L004, mSARS2_19_S37_L004, mSARS2_20_S38_L004, mSARS2_21_S39_L004, mSARS2_22_S40_L004, mSARS2_23_S41_L004,
     mSARS2_24_S42_L004, mSARS2_25_S43_L004, mSARS2_26_S44_L004, mSARS2_27_S45_L004, mSARS2_28_S46_L004, mSARS2_29_S47_L004,
     mSARS2_30_S48_L004, mSARS2_31_S49_L004, mSARS2_32_S50_L004, mSARS2_33_S51_L004, mSARS2_34_S52_L004, mSARS2_35_S53_L004,
     mSARS2_36_S54_L004, mSARS2_37_S55_L004, mSARS2_38_S56_L004, mSARS2_39_S57_L004, mSARS2_40_S58_L004, mSARS2_41_S59_L004,
     mSARS2_42_S60_L004, mSARS2_43_S61_L004, mSARS2_44_S62_L004, mSARS2_45_S63_L004, mSARS2_46_S64_L004, mSARS2_64_S18_L003,
     mSARS2_79_S65_L004, mSARS2_80_S66_L004, mSARS2_65_S19_L003, mSARS2_81_S67_L004, mSARS2_66_S20_L003, mSARS2_82_S68_L004,
     mSARS2_83_S69_L004, mSARS2_67_S21_L003, mSARS2_68_S22_L003, mSARS2_84_S70_L004, mSARS2_69_S23_L003, mSARS2_85_S71_L004,
     mSARS2_86_S72_L004, mSARS2_70_S24_L003, mSARS2_87_S73_L004, mSARS2_71_S25_L003, mSARS2_88_S74_L004, mSARS2_72_S26_L003,
     mSARS2_89_S75_L004, mSARS2_73_S27_L003, mSARS2_90_S76_L004, mSARS2_74_S28_L003, mSARS2_75_S29_L003, mSARS2_91_S77_L004,
     mSARS2_76_S30_L003, mSARS2_77_S31_L003, mSARS2_92_S78_L004, mSARS2_78_S32_L003, mSARS2_93_S79_L004, mSARS2_94_S80_L004,
     mSARS2_95_S81_L004, mSARS2_96_S82_L004, mSARS2_97_S83_L004, mSARS2_98_S84_L004, mSARS2_99_S85_L004,
     #BATCH 1 FROM MCGILL
     MCGILL1, MCGILL2, MCGILL3, MCGILL4,
     #BATCH 2 FROM MCGILL
     MCGILL5, MCGILL6, MCGILL7, MCGILL8, MCGILL9, MCGILL10, MCGILL11, MCGILL12, MCGILL13, MCGILL14,
     #BATCH 3 FROM MCGILL
     MCGILL15, MCGILL16, MCGILL17, MCGILL18, MCGILL19, MCGILL20, MCGILL21, MCGILL22, MCGILL23, MCGILL24,
     #BATCH 4 FROM MCGILL
     MCGILL25, MCGILL26, MCGILL27, MCGILL28, MCGILL29, MCGILL30, MCGILL31, MCGILL32,
     #BATCH 5 FROM MCGILL
     MCGILL33, MCGILL34, MCGILL35, MCGILL36, MCGILL37, MCGILL38, MCGILL39, MCGILL40, MCGILL41, MCGILL42,
     #BATCH 6 FROM MCGILL
     MCGILL43, MCGILL44, MCGILL45, MCGILL46, MCGILL47, MCGILL48, MCGILL49, MCGILL50, MCGILL51, MCGILL52,
     #HEALTHY VOLUNTEERS -- SSLP MEYER
     SSLP_MEYER_IRBHLY1, SSLP_MEYER_IRBHLY2, SSLP_MEYER_IRBHLY3, SSLP_MEYER_IRBHLY4, SSLP_MEYER_IRBHLY5,
     #HEALTHY VOLUNTEERS -- SRSLY
     SRSLY_HLY1, SRSLY_HLY2, SRSLY_HLY3, SRSLY_HLY4, SRSLY_HLY5,
     #HEALTHY VOLUNTEERS -- SWIFT
     #SWIFTHLY1, SWIFTHLY2, SWIFTHLY3, SWIFTHLY4,
     #HEALTHY COLUNTEERS -- SWIFT PE
     SWIFTHLY1PE, SWIFTHLY2PE, SWIFTHLY3PE, SWIFTHLY4PE,
     #meyer_test, srsly_test, swift_SE_test, mcgill_test, ucsf_pe150_L004, ucsf_pe100_L004
     # RESEQUENCED MCGILL SAMPLES AND BIOLOGICAL DUPLICATES AND BATCH 7
     MCGILL1CAT, MCGILL23CAT, MCGILL26CAT, MCGILL17DUP, MCGILL53, MCGILL54, MCGILL29DUP
     ]

CONTROLS:
     []
     #[MCGILLLMC1, MCGILLHMC1, MCGILLLMC2, MCGILLHMC2, MCGILLLMC3, MCGILLHMC3,
     #MCGILLLMC4, MCGILLHMC4, MCGILLLMC5, MCGILLHMC5,  MCGILLLMC6, MCGILLHMC6,
     #LMCB17, HMCB17, #MEYER HEALTHY MCs
     ##SRSLY_LMCB18, SRSLY_HMCB18,
     #SWIFTLMCB, SWIFTHMCB,
     #[SWIFTLMCBPE, SWIFTHMCBPE]


REFERENCE_METHYLOMES:
     [bcell_1, bcell_2, bcell_3, bcell_4, bcell_5, bcell_6, bcell_7, bcell_8, bcell_9,
#     bladder_1,
     colon_1, colon_2, colon_3, colon_4, colon_5, colon_6, colon_7, colon_8, colon_9, colon_10, colon_11, colon_12,
     colon_13, colon_14, colon_15, colon_16, colon_17, colon_18, colon_19, colon_20, colon_21, colon_22, colon_23, colon_24, colon_25,
     dendritic_1, dendritic_2,
     eosinophil_1, eosinophil_2, eosinophil_3, eosinophil_4, eosinophil_5,
     erythroblast_1, erythroblast_2,
     heart_1, heart_2, heart_3, heart_4,
     hsc_1, hsc_2, hsc_3, hsc_4, hsc_5, hsc_6, hsc_7,
     kidney_1, kidney_2, kidney_3, kidney_4, kidney_5, kidney_6, kidney_7, kidney_8, kidney_9, kidney_10,
     liver_1, liver_2, liver_3, liver_4, liver_5, liver_6, liver_7, liver_8, liver_9,
     lung_1, lung_2, lung_3, lung_4, lung_5, lung_6,
     macrophage_1, macrophage_2, macrophage_3, macrophage_4, macrophage_5, macrophage_6, macrophage_7, macrophage_8, macrophage_9, macrophage_10,
     monocyte_1, monocyte_2, monocyte_3, monocyte_4, monocyte_5, monocyte_6,
     neutrophil_1, neutrophil_2, neutrophil_3, neutrophil_4, neutrophil_5, neutrophil_6, neutrophil_7,
     nkcell_1, nkcell_2,
     pancreas_1, pancreas_2, pancreas_3, pancreas_4, pancreas_5, pancreas_6, pancreas_7,
     progenitor_1, progenitor_2, progenitor_3, progenitor_4, progenitor_5, progenitor_6, progenitor_7, progenitor_8, progenitor_9, progenitor_10,
     progenitor_11, progenitor_12, progenitor_13, progenitor_14, progenitor_15, progenitor_16,
     skin_1, skin_2,
     spleen_1, spleen_2, spleen_3, spleen_4,
     tcell_1, tcell_2, tcell_3, tcell_4, tcell_5, tcell_6, tcell_7, tcell_8, tcell_9, tcell_10, tcell_11, tcell_12]

KNOWNCHROMO:
     [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY]

#Locations
CLUSTER: / #default is / for cluster2
DATA: workdir/apc88/WGBS_pipeline/Data/
SEQUENCING_PREP_TABLE: /workdir/apc88/WGBS_pipeline/sequencing_prep.tsv
MEYER_ADAPTORS: /workdir/apc88/WGBS_pipeline/references/adapter_sequences/adapters_meyer.fa
SRSLY_ADAPTORS: /workdir/apc88/WGBS_pipeline/references/adapter_sequences/adapters_srsly.fa
SA_ADAPTORS: /workdir/apc88/WGBS_pipeline/references/adapter_sequences/adapters_sa.fa
METHYLOME_TABLE: /workdir/apc88/WGBS_pipeline/reference_methylomes.tsv

#REFERENCES: /workdir/apc88/WGBS_pipeline/references/
#REFERENCE_METHYLOMES: /workdir/apc88/WGBS_pipeline/Reference_Methylomes/MethylMatrix/all_chr/
#ADAPTOR_SEQUENCES: /workdir/apc88/WGBS_pipeline/references/adapter_sequences/adapters_meyer.fa

#References
HG19METH: /workdir/apc88/WGBS_pipeline/references/hg19_Bismark/
CTLMETH: /workdir/apc88/WGBS_pipeline/references/controls_Bismark/
#HG19: /workdir/apc88/WGBS_pipeline/references/hg19_Bismark/hg19.fa

#CTLREF: /workdir/apc88/WGBS_pipeline/references/mic_control/
#CTLREF_fasta: /workdir/apc88/WGBS_pipeline/references/mic_control/mic.fa
# Programs
SPRING: /workdir/apc88/WGBS_pipeline/software/SPRING/build/spring
BISMARKINDEX: /workdir/apc88/WGBS_pipeline/software/Bismark-0.22.1/bismark_genome_preparation
BBDUK: /workdir/apc88/WGBS_pipeline/software/bbmap/bbduk.sh
BISMARK: /workdir/apc88/WGBS_pipeline/software/Bismark-0.22.1/bismark
RMDUPS : /workdir/apc88/WGBS_pipeline/software/Bismark-0.22.1/deduplicate_bismark
METHEXT: /workdir/apc88/WGBS_pipeline/software/Bismark-0.22.1/bismark_methylation_extractor
SGREP: /programs/sgrep_sorted/bin/sgrep
HSBLASTN: /workdir/apc88/WGBS_pipeline/software/hs-blastn-src/hs-blastn
REPAIR: /workdir/apc88/WGBS_pipeline/software/bbmap/repair.sh
TRIM_GALORE: /workdir/apc88/WGBS_pipeline/software/TrimGalore-0.6.5
#Scripts
GRAMMY_GDT: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_gdt.py
GRAMMY_RDT: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_rdt.py
GRAMMY_PRE: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_pre.py
GRAMMY_EM: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_em.py
GRAMMY_POST: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_post.py
GRAMMY_REF_FASTA: /workdir/apc88/WGBS_pipeline/grammy/NCBIGenomes06_CT
#PICARD_MARKDUP: java -jar /workdir/apc88/WGBS_pipeline/software/picard.jar MarkDuplicates
METHPIPETOMR: /workdir/apc88/WGBS_pipeline/software/methpipe-3.4.3/bin/to-mr
METHPIPEBSRATE: /workdir/apc88/WGBS_pipeline/software/methpipe-3.4.3/bin/bsrate

HMMCOPY_FA_BW: /workdir/apc88/WGBS_pipeline/software/HMMcopy/util/mappability/generateMap.pl
HMMCOPY_MAP: /workdir/apc88/WGBS_pipeline/software/HMMcopy/bin/mapCounter
HMMCOPY_GC: /workdir/apc88/WGBS_pipeline/software/HMMcopy/bin/gcCounter
HMMCOPY_READCOUNTER: /workdir/apc88/WGBS_pipeline/software/HMMcopy/bin/readCounter
SEQTK: /workdir/apc88/WGBS_pipeline/software/seqtk/seqtk
bigWigToBedGraph: /programs/ucsc/userApps/bin/bigWigToBedGraph
CROSSMAP: /workdir/apc88/WGBS_pipeline/software/CrossMap-0.2.7/bin/CrossMap.py
METILENE: /workdir/apc88/WGBS_pipeline/software/metilene_v0.2-7/metilene_linux64
#MOSDEPTH: /workdir/apc88/WGBS_pipeline/software/mosdepth
# Eilon SCRIPTS_PATH
#ddcfDNA: /workdir/apc88/WGBS_pipeline/software/ddcfDNA/ddcfDNA-master

# Programs
#FASTQPAIR : /workdir/apc88/WGBS_pipeline/software/fastq-pair/build/fastq_pair

#Strings
AUTOSOMALCHROMO: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22
