SAMPLES:
     #['BIG']
     [
     #FASTQs go here
     ]

REFERENCE_METHYLOMES:
     [bcell_1, bcell_2, bcell_3, bcell_4, bcell_5, bcell_6, bcell_7, bcell_8, bcell_9,
#     bladder_1,
     colon_1, colon_2, colon_3, colon_4, colon_5, colon_6, colon_7, colon_8, colon_9, colon_10, colon_11, colon_12,
     colon_13, colon_14, colon_15, colon_16, colon_17, colon_18, colon_19, colon_20, colon_21, colon_22, colon_23, colon_24, colon_25,
     dendritic_1, dendritic_2,
     eosinophil_1, eosinophil_2, eosinophil_3, eosinophil_4, eosinophil_5,
     erythroblast_1, erythroblast_2,
     heart_1, heart_2, heart_3, heart_4,
     hsc_1, hsc_2, hsc_3, hsc_4, hsc_5, hsc_6, hsc_7,
     kidney_1, kidney_2, kidney_3, kidney_4, kidney_5, kidney_6, kidney_7, kidney_8, kidney_9, kidney_10,
     liver_1, liver_2, liver_3, liver_4, liver_5, liver_6, liver_7, liver_8, liver_9,
     lung_1, lung_2, lung_3, lung_4, lung_5, lung_6,
     macrophage_1, macrophage_2, macrophage_3, macrophage_4, macrophage_5, macrophage_6, macrophage_7, macrophage_8, macrophage_9, macrophage_10,
     monocyte_1, monocyte_2, monocyte_3, monocyte_4, monocyte_5, monocyte_6,
     neutrophil_1, neutrophil_2, neutrophil_3, neutrophil_4, neutrophil_5, neutrophil_6, neutrophil_7,
     nkcell_1, nkcell_2,
     pancreas_1, pancreas_2, pancreas_3, pancreas_4, pancreas_5, pancreas_6, pancreas_7,
     progenitor_1, progenitor_2, progenitor_3, progenitor_4, progenitor_5, progenitor_6, progenitor_7, progenitor_8, progenitor_9, progenitor_10,
     progenitor_11, progenitor_12, progenitor_13, progenitor_14, progenitor_15, progenitor_16,
     skin_1, skin_2,
     spleen_1, spleen_2, spleen_3, spleen_4,
     tcell_1, tcell_2, tcell_3, tcell_4, tcell_5, tcell_6, tcell_7, tcell_8, tcell_9, tcell_10, tcell_11, tcell_12]

KNOWNCHROMO:
     [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY]

#Locations
CLUSTER: / #default is / for cluster2
DATA: workdir/apc88/WGBS_pipeline/Data/
SEQUENCING_PREP_TABLE: /workdir/apc88/WGBS_pipeline/sequencing_prep.tsv
MEYER_ADAPTORS: /workdir/apc88/WGBS_pipeline/references/adapter_sequences/adapters_meyer.fa
SRSLY_ADAPTORS: /workdir/apc88/WGBS_pipeline/references/adapter_sequences/adapters_srsly.fa
SA_ADAPTORS: /workdir/apc88/WGBS_pipeline/references/adapter_sequences/adapters_sa.fa
METHYLOME_TABLE: /workdir/apc88/WGBS_pipeline/reference_methylomes.tsv

#REFERENCES: /workdir/apc88/WGBS_pipeline/references/
#REFERENCE_METHYLOMES: /workdir/apc88/WGBS_pipeline/Reference_Methylomes/MethylMatrix/all_chr/
#ADAPTOR_SEQUENCES: /workdir/apc88/WGBS_pipeline/references/adapter_sequences/adapters_meyer.fa

#References
HG19METH: /workdir/apc88/WGBS_pipeline/references/hg19_Bismark/
CTLMETH: /workdir/apc88/WGBS_pipeline/references/controls_Bismark/
#HG19: /workdir/apc88/WGBS_pipeline/references/hg19_Bismark/hg19.fa

#CTLREF: /workdir/apc88/WGBS_pipeline/references/mic_control/
#CTLREF_fasta: /workdir/apc88/WGBS_pipeline/references/mic_control/mic.fa
# Programs
SPRING: /workdir/apc88/WGBS_pipeline/software/SPRING/build/spring
BISMARKINDEX: /workdir/apc88/WGBS_pipeline/software/Bismark-0.22.1/bismark_genome_preparation
BBDUK: /workdir/apc88/WGBS_pipeline/software/bbmap/bbduk.sh
BISMARK: /workdir/apc88/WGBS_pipeline/software/Bismark-0.22.1/bismark
RMDUPS : /workdir/apc88/WGBS_pipeline/software/Bismark-0.22.1/deduplicate_bismark
METHEXT: /workdir/apc88/WGBS_pipeline/software/Bismark-0.22.1/bismark_methylation_extractor
SGREP: /programs/sgrep_sorted/bin/sgrep
HSBLASTN: /workdir/apc88/WGBS_pipeline/software/hs-blastn-src/hs-blastn
REPAIR: /workdir/apc88/WGBS_pipeline/software/bbmap/repair.sh
TRIM_GALORE: /workdir/apc88/WGBS_pipeline/software/TrimGalore-0.6.5
#Scripts
GRAMMY_GDT: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_gdt.py
GRAMMY_RDT: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_rdt.py
GRAMMY_PRE: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_pre.py
GRAMMY_EM: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_em.py
GRAMMY_POST: /workdir/apc88/WGBS_pipeline/software/GRAMMy/grammy/grammy_post.py
GRAMMY_REF_FASTA: /workdir/apc88/WGBS_pipeline/grammy/NCBIGenomes06_CT
#PICARD_MARKDUP: java -jar /workdir/apc88/WGBS_pipeline/software/picard.jar MarkDuplicates
METHPIPETOMR: /workdir/apc88/WGBS_pipeline/software/methpipe-3.4.3/bin/to-mr
METHPIPEBSRATE: /workdir/apc88/WGBS_pipeline/software/methpipe-3.4.3/bin/bsrate

HMMCOPY_FA_BW: /workdir/apc88/WGBS_pipeline/software/HMMcopy/util/mappability/generateMap.pl
HMMCOPY_MAP: /workdir/apc88/WGBS_pipeline/software/HMMcopy/bin/mapCounter
HMMCOPY_GC: /workdir/apc88/WGBS_pipeline/software/HMMcopy/bin/gcCounter
HMMCOPY_READCOUNTER: /workdir/apc88/WGBS_pipeline/software/HMMcopy/bin/readCounter
SEQTK: /workdir/apc88/WGBS_pipeline/software/seqtk/seqtk
bigWigToBedGraph: /programs/ucsc/userApps/bin/bigWigToBedGraph
CROSSMAP: /workdir/apc88/WGBS_pipeline/software/CrossMap-0.2.7/bin/CrossMap.py
METILENE: /workdir/apc88/WGBS_pipeline/software/metilene_v0.2-7/metilene_linux64
#MOSDEPTH: /workdir/apc88/WGBS_pipeline/software/mosdepth
# Eilon SCRIPTS_PATH
#ddcfDNA: /workdir/apc88/WGBS_pipeline/software/ddcfDNA/ddcfDNA-master

# Programs
#FASTQPAIR : /workdir/apc88/WGBS_pipeline/software/fastq-pair/build/fastq_pair

#Strings
AUTOSOMALCHROMO: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22
